#!/usr/bin/env bash

if
  [[ -s "/home/orchid/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/environment" ]]
then
  source "/home/orchid/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/orchid/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/environment'" >&2
  exit 1
fi
